import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {openApp,ready,loadNative,setFixturePolicy,saveDownload,dropText,E,INPUT} from './browser_common.mjs';
const require=createRequire(import.meta.url),yaml=require('../web/vendor/js-yaml.umd.min.js');
const input=await fs.readFile(INPUT),source=yaml.load(input.toString('utf8'),{schema:yaml.CORE_SCHEMA});
const dump=data=>yaml.dump(data,{schema:yaml.CORE_SCHEMA,noRefs:true,forceQuotes:true,quoteStyle:'double',lineWidth:1000});
const app=await openApp(),{page}=app,scenarios=[];
const pass=name=>{scenarios.push(name);console.log('PASS '+name);};
async function error(){await page.waitForFunction(()=>document.body.dataset.state==='error');assert.equal(await page.locator('#workbench').isHidden(),true);assert.equal(await page.locator('#download').isDisabled(),true);}
try{
 assert.equal(await page.locator('html').getAttribute('lang'),'ja');await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(n=>n===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#main').evaluate(n=>n===document.activeElement),true);pass('Japanese default and keyboard skip link');
 await page.locator('#sample').focus();await page.keyboard.press('Enter');await ready(page);assert.equal(await page.locator('#note-count').textContent(),'6');assert.equal(await page.locator('#change-count').textContent(),'0');assert.equal(await page.locator('#download').isDisabled(),true);assert.equal(await page.locator('input[data-list]:checked').count(),0);pass('Keyboard sample has no automatic cleanup and requires acknowledgment');
 await page.locator('#lang-en').click();await page.locator('#file-input').focus();await page.screenshot({path:path.join(E,'ui-keyboard-file-control.png')});const chooserEvent=page.waitForEvent('filechooser');await page.keyboard.press('Enter');const chooser=await chooserEvent;assert.equal(chooser.isMultiple(),false);await chooser.setFiles(INPUT);await ready(page);assert.equal(await page.locator('#file-input').inputValue(),'');pass('Keyboard activation opens the real browser file chooser; its value resets for same-file reselection');
 await page.locator('#ack').focus();await page.keyboard.press('Space');await saveDownload(page,'#download','ui-noop-copy.ustx');assert.deepEqual(await fs.readFile(path.join(E,'ui-noop-copy.ustx')),input);pass('Real native input with no selected settings downloads byte-identically');
 await page.locator('#policy-singer').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#change-count').textContent(),'2');assert.equal(await page.locator('#ack').isChecked(),false);assert.equal(await page.locator('#download').isDisabled(),true);await saveDownload(page,'#report','ui-singer-only-review.json');const singerReview=JSON.parse(await fs.readFile(path.join(E,'ui-singer-only-review.json'),'utf8'));assert.equal(singerReview.acknowledged,false);assert.ok(singerReview.changes.every(c=>c.path[0]==='tracks'&&c.path[2]==='singer'));assert.equal(singerReview.counts.parts,0);pass('Independent singer choice exposes only two track changes and resets acknowledgment');
 await page.locator('#reset-policy').click();assert.equal(await page.locator('#change-count').textContent(),'0');await setFixturePolicy(page);assert.equal(await page.locator('#diff-rows tr').count(),37);assert.match(await page.locator('#affected-counts').textContent(),/2 tracks.*3 parts.*6 notes/);pass('Explicit whole-project policy previews every one of 37 original values');
 await page.locator('#ack').check();await saveDownload(page,'#download','ui-first-copy.ustx');await saveDownload(page,'#download','ui-repeat-copy.ustx');assert.deepEqual(await fs.readFile(path.join(E,'ui-first-copy.ustx')),await fs.readFile(path.join(E,'ui-repeat-copy.ustx')));pass('Repeated export is complete and deterministic');
 await loadNative(page);assert.equal(await page.locator('#ack').isChecked(),false);assert.equal(await page.locator('#change-count').textContent(),'0');assert.equal(await page.locator('#structure-rows tr').count(),3);const structure=await page.locator('#structure-rows tr').allTextContents();assert.ok(structure[0].includes('1920')&&structure[1].includes('3840')&&structure[2].includes('960'));pass('Repeated real-file selection clears policy/review and retains original part structure');
 const hostile=structuredClone(source);hostile.name='<img src="https://example.invalid/never"><script>window.__executed=true</script>';hostile.voice_parts[0].notes[0].phoneme_overrides[0].phoneme='<svg onload="window.__executed=true">';await dropText(page,dump(hostile));await ready(page);await page.locator('#override-phoneme').check();assert.equal(await page.locator('#project-name img').count(),0);assert.equal(await page.locator('#diff-rows svg').count(),0);assert.equal(await page.evaluate(()=>window.__executed),undefined);assert.match(await page.locator('#project-name').textContent(),/<script>/);pass('Script-looking project names and affected values stay literal text');
 const old=structuredClone(source);old.ustx_version='0.9';await dropText(page,dump(old));await error();await page.locator('#lang-ja').click();assert.match(await page.locator('#error').textContent(),/読み込めません/);await page.locator('#lang-en').click();assert.match(await page.locator('#error').textContent(),/Cannot read/);pass('Unsupported version removes stale output and errors follow the language');
 const precisionDownloads=[];const precisionRecord=d=>precisionDownloads.push(d.suggestedFilename());page.on('download',precisionRecord);await page.locator('#file-input').setInputFiles(path.join(E,'precision-exact.ustx'));await error();assert.equal(await page.locator('#report').isDisabled(),true);await page.waitForTimeout(50);assert.deepEqual(precisionDownloads,[]);page.off('download',precisionRecord);
 await fs.writeFile(path.join(E,'browser-precision-result.json'),JSON.stringify({status:'pass',exactDecimalRejectedBeforeOutput:true,inputSha256:crypto.createHash('sha256').update(await fs.readFile(path.join(E,'precision-exact.ustx'))).digest('hex'),downloads:precisionDownloads},null,2)+'\n');pass('Actual browser rejects the native float32-midpoint input before any output');
 await dropText(page,input.toString('utf8')+'\nanchor_test: &anchor [1]\nalias_test: *anchor\n');await error();await dropText(page,input.toString('utf8')+'\nname: duplicate\n');await error();pass('Anchors/aliases and duplicate YAML keys reject the whole input');
 const waves=structuredClone(source);waves.wave_parts=[{relative_path:'../external.wav'}];await dropText(page,dump(waves));await error();pass('Wave references are rejected without external file access');
 await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='oversize.ustx')window.__oversizeRead=true;if(this.name==='older.ustx'){window.__delayedStarted=true;await new Promise(resolve=>setTimeout(resolve,300));}return original.call(this);};window.__oversizeRead=false;window.__delayedStarted=false;});
 await page.evaluate(()=>{const d=new DataTransfer();d.items.add(new File([new Uint8Array(8*1024*1024+1)],'oversize.ustx'));document.getElementById('drop-zone').dispatchEvent(new DragEvent('drop',{dataTransfer:d,bubbles:true}));});await error();assert.equal(await page.evaluate(()=>window.__oversizeRead),false);pass('Input byte limit is enforced before File.arrayBuffer');
 await dropText(page,input.toString('utf8'),'wrong.txt');await error();await page.evaluate(()=>{const d=new DataTransfer();d.items.add(new File(['a'],'one.ustx'));d.items.add(new File(['b'],'two.ustx'));document.getElementById('drop-zone').dispatchEvent(new DragEvent('drop',{dataTransfer:d,bubbles:true}));});await error();pass('Wrong file kind and multiple input files fail explicitly');
 const older=structuredClone(source);older.name='Older async project';await dropText(page,dump(older),'older.ustx');await page.waitForFunction(()=>window.__delayedStarted);await page.locator('#sample').click();await ready(page);await page.waitForTimeout(380);assert.notEqual(await page.locator('#project-name').textContent(),'Older async project');pass('A newer input wins over a delayed earlier read');
 await page.evaluate(()=>window.__delayedStarted=false);await dropText(page,dump(older),'older.ustx');await page.waitForFunction(()=>window.__delayedStarted);await page.locator('#clear').click();await page.waitForTimeout(380);assert.equal(await page.evaluate(()=>document.body.dataset.state),'empty');assert.equal(await page.locator('#project-name').textContent(),'');assert.equal(await page.locator('#diff-rows tr').count(),0);pass('Clear cancels pending reads without resurrecting file or review data');
 await page.evaluate(()=>{const input=document.getElementById('file-input');input.value='';input.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await page.evaluate(()=>document.body.dataset.state),'empty');pass('Explicit empty input change leaves no stale review, without claiming OS-picker cancellation');
 await loadNative(page);await setFixturePolicy(page);await page.locator('#ack').check();
 await page.evaluate(()=>{const original=crypto.subtle.digest.bind(crypto.subtle);crypto.subtle.digest=async(...args)=>{if(window.__delayDigest){window.__digestStarted=true;await new Promise(resolve=>setTimeout(resolve,300));}return original(...args);};window.__delayDigest=true;window.__digestStarted=false;});
 const lateDownloads=[];const record=d=>lateDownloads.push(d.suggestedFilename());page.on('download',record);await page.locator('#download').click();await page.waitForFunction(()=>window.__digestStarted);await page.locator('#policy-singer').uncheck();assert.equal(await page.locator('#ack').isChecked(),false);await page.evaluate(()=>window.__delayDigest=false);await page.waitForTimeout(400);assert.deepEqual(lateDownloads,[]);page.off('download',record);
 await page.locator('#ack').check();await saveDownload(page,'#download','ui-after-stale-export.ustx');const afterStale=yaml.load(await fs.readFile(path.join(E,'ui-after-stale-export.ustx'),'utf8'),{schema:yaml.CORE_SCHEMA});assert.equal(afterStale.tracks[0].singer,source.tracks[0].singer);assert.equal(afterStale.tracks[1].singer,source.tracks[1].singer);assert.deepEqual(afterStale.tracks[0].renderer_settings,{});assert.equal(await page.locator('#change-count').textContent(),'35');pass('Policy change cancels an in-flight export and prevents stale conversion-cache reuse');
 function larger(count){const p=structuredClone(source);p.voice_parts=Array.from({length:count},(_,i)=>({...structuredClone(source.voice_parts[i%3]),name:'Review part '+(i+1),position:i*3840}));return p;}
 await dropText(page,dump(larger(8)));await ready(page);await setFixturePolicy(page,82);assert.equal(await page.locator('#diff-rows tr').count(),50);await page.locator('#next').click();assert.equal(await page.locator('#diff-rows tr').count(),32);assert.match(await page.locator('#page-range').textContent(),/51–82/);await page.locator('#previous').click();await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));assert.equal(await page.locator('#diff-rows tr').count(),82);await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));assert.equal(await page.locator('#diff-rows tr').count(),50);pass('Paginated review exposes all rows and print restores the complete change list');
 await dropText(page,dump(larger(225)));await ready(page);await setFixturePolicy(page,2035);assert.equal(await page.evaluate(()=>document.body.dataset.state),'blocked');await page.locator('#ack').check();assert.equal(await page.locator('#download').isDisabled(),true);assert.match(await page.locator('#error').textContent(),/2,000/);await page.locator('#reset-policy').click();await ready(page);assert.equal(await page.locator('#error').isHidden(),true);pass('Two-thousand-change UI cap blocks export and recovers when selection is reduced');
 await loadNative(page);await setFixturePolicy(page);await page.locator('#lang-en').click();await page.screenshot({path:path.join(E,'ui-en-desktop.png'),fullPage:true});await page.screenshot({path:path.join(E,'ui-en-desktop-top.png')});await page.locator('#diff-container').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(E,'ui-en-desktop-diff.png')});await page.locator('#lang-ja').click();await page.screenshot({path:path.join(E,'ui-ja-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(E,'ui-ja-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#lang-en').click();await page.screenshot({path:path.join(E,'ui-en-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#diff-container').evaluate(n=>n.scrollLeft=n.scrollWidth);const edge=await page.locator('#diff-container').evaluate(n=>{const box=n.getBoundingClientRect(),cell=n.querySelector('thead th:last-child').getBoundingClientRect();return {left:box.left,right:box.right,cellLeft:cell.left,cellRight:cell.right,overflow:n.scrollWidth>n.clientWidth};});assert.equal(edge.overflow,true);assert.ok(edge.cellLeft>=edge.left-1&&edge.cellRight<=edge.right+1);await page.locator('#diff-container').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(E,'ui-en-mobile-table-end.png')});pass('JA/EN desktop and 390px views preserve policy/diff and expose the complete final column');
 await page.setViewportSize({width:1440,height:1040});for(const language of ['en','ja']){await page.emulateMedia({media:'screen'});await page.locator('#lang-'+language).click();await page.emulateMedia({media:'print'});await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));assert.equal(await page.locator('#diff-rows tr').count(),37);const stem=language==='en'?'ui-print':'ui-print-ja';await page.screenshot({path:path.join(E,stem+'.png'),fullPage:true});await page.pdf({path:path.join(E,stem+'.pdf'),format:'A4',landscape:true,printBackground:true});await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));}await page.emulateMedia({media:'screen'});pass('JA/EN print evidence includes all 37 affected values, original structure and retained-information limits');
 assert.deepEqual(app.errors,[]);assert.deepEqual(app.network,[]);pass('Exact packaged file-protocol app has no console/page errors or HTTP requests');
 await fs.writeFile(path.join(E,'browser-ui-result.json'),JSON.stringify({status:'pass',scenarios,consoleErrors:app.errors,networkRequests:app.network},null,2)+'\n');
}catch(error){await page.screenshot({path:path.join(E,'FAILED-browser-test.png'),fullPage:true});throw error;}finally{await app.browser.close();}
