(function () {
  'use strict';
  const C = globalThis.VoiceSlateCore;
  const $ = id => document.getElementById(id);
  const own = (value,key) => Object.prototype.hasOwnProperty.call(value,key);
  const PAGE_SIZE = 50, MAX_CHANGES = 2000;
  let language = 'ja', model = null, policy = emptyPolicy(), preview = null;
  let sourceName = '', revision = 0, busy = false, pageIndex = 0, conversion = null;
  let statusKey = '', errorKey = '', errorDetail = '', printing = false;
  const words = {
    ja: {
      skip:'本文へ移動',local:'ファイルはこのブラウザ内だけ',title:'渡す前に、選んだ設定だけ。',lead:'歌詞や音符、パートの構成を保ちながら、共有用の USTX コピーを整えます。',scope:'音源・レンダー・選んだ表情設定を確認してクリア。互換性や匿名化を保証するツールではありません。',
      sourceStep:'01 / SOURCE',sourceTitle:'保存した USTX を選ぶ',sourceHelp:'元ファイルは変更しません。ファイルをひとつ選ぶか、ここにドロップしてください。',choose:'USTX を選ぶ',sample:'サンプルで試す',clear:'クリア',projectLabel:'CURRENT PROJECT',tracks:'トラック',parts:'パート',notes:'音符',
      chooseStep:'02 / CHOOSE',policyTitle:'クリアする項目を選ぶ',policyHelp:'最初は何も選択されません。選んだ設定だけ、プロジェクト全体に適用します。',bindings:'トラック設定',singer:'音源 ID',singerHelp:'各トラックの音源への参照',render:'レンダーの割り当て',renderHelp:'renderer / resampler / wavtool',color:'トラックの色',colorHelp:'標準色 Blue に戻す',overrides:'音素の個別指定',expressions:'音符ごとの表情値',expressionsHelp:'選んだ略号の値を削除。定義は保持します。',curves:'パートのカーブ',curvesHelp:'選んだカーブだけを削除。音符のピッチ点とビブラートは保持します。',resetPolicy:'選択をすべて解除',
      reviewStep:'03 / REVIEW',reviewTitle:'変更前と変更後を確認',changes:'変更',retained:'パート・音符・タイミング・歌詞・ピッチ・ビブラート・定義と、選ばなかった値は保持します。',noChanges:'設定を選ぶと、変更される値がここに表示されます。選択がない場合は元のバイト列をそのままコピーします。',where:'場所',before:'変更前',after:'変更後',previous:'前へ',next:'次へ',reportNote:'JSON レポートには、すべての変更箇所と元の値を含みます。レポートにも共有したくない情報が含まれる場合があります。',
      copyStep:'04 / COPY',exportTitle:'確認した設定でコピーを作る',privacy:'匿名化ではありません。名前・歌詞・コメントや選択外の設定は残ります。音源の互換性や音声の再現も保証しません。',ack:'変更する設定と元の値を確認し、選択外の情報が残ることを理解しました。',download:'USTX コピーを書き出す',report:'JSON レポート',print:'確認表を印刷',structureTitle:'保持するパート構成',structureHelp:'パートの位置・長さと音符数を確認できます。',track:'トラック',part:'パート',position:'位置 (tick)',duration:'長さ (tick)',limits:'UTF-8 · 最大 8 MiB · USTX 0.10 の音声パートのみ。1 回の確認は最大 2,000 変更。YAML の未対応構文や不正なデータは拒否します。',footerScope:'ローカル処理・アカウント不要・ネットワーク通信なし',sourceLink:'ソースと検証',
      loading:'ファイルを確認しています…',ready:'元データを確認しました。クリアする項目を選んでください。',updated:'選択を更新しました。確認欄は解除されています。',downloaded:'USTX コピーを書き出しました。元ファイルは変更していません。',reportSaved:'JSON レポートを書き出しました。',exporting:'確認したコピーを作成しています…',empty:'ファイルと確認内容をクリアしました。',bad:'このファイルは読み込めません。対応形式・YAML の構文・データの上限を確認してください。',size:'ファイルサイズが 8 MiB の上限を超えています。本文は読み込んでいません。',file:'拡張子 .ustx のファイルをひとつ選んでください。',tooMany:'選んだ変更が 2,000 件を超えています。項目を減らして、もう一度確認してください。',failedExport:'コピーを作成できませんでした。確認欄を解除しました。',removed:'削除',notPresent:'値なし',noneAvailable:'この種類の指定はありません。',affected:(c)=>`影響する範囲：${c.tracks} トラック・${c.parts} パート・${c.notes} 音符`,range:(a,b,n)=>`${a}–${b} / ${n} 件`,noteLabel:(n)=>`音符 ${n}`,phonemeLabel:(n)=>`音素 ${n}`,partFallback:(n)=>`パート ${n}`,trackFallback:(n)=>`トラック ${n}`,
      fieldNames:{phoneme:'音素エイリアス',offset:'音素オフセット',preutter_delta:'先行発声の差分',overlap_delta:'オーバーラップの差分',attack_time_delta:'アタック時間の差分',release_time_delta:'リリース時間の差分',singer:'音源 ID',track_color:'トラックの色',renderer:'Renderer',resampler:'Resampler',wavtool:'Wavtool'}
    },
    en: {
      skip:'Skip to content',local:'Files stay in this browser',title:'Choose what travels with the score.',lead:'Prepare a sharing copy of your USTX while keeping the original notes, words and part structure.',scope:'Review and clear selected singer, render and expression settings. Compatibility and anonymization are outside this tool’s scope.',
      sourceStep:'01 / SOURCE',sourceTitle:'Choose a saved USTX',sourceHelp:'The original file stays unchanged. Choose one file, or drop it here.',choose:'Choose USTX file',sample:'Try the sample',clear:'Clear',projectLabel:'CURRENT PROJECT',tracks:'tracks',parts:'parts',notes:'notes',
      chooseStep:'02 / CHOOSE',policyTitle:'Choose settings to clear',policyHelp:'Nothing is selected initially. Your choices apply across the whole project.',bindings:'Track settings',singer:'Singer IDs',singerHelp:'References to each track’s singer',render:'Render bindings',renderHelp:'renderer / resampler / wavtool',color:'Track colors',colorHelp:'Restore the native default, Blue',overrides:'Phoneme overrides',expressions:'Per-note expression values',expressionsHelp:'Remove values for chosen abbreviations. Keep their definitions.',curves:'Part curves',curvesHelp:'Remove chosen curves. Keep note pitch points and vibrato.',resetPolicy:'Clear all selections',
      reviewStep:'03 / REVIEW',reviewTitle:'Review every affected value',changes:'changes',retained:'Keep parts, notes, timing, lyrics, pitch, vibrato, definitions and all unselected values.',noChanges:'Choose settings to see their affected values here. With nothing selected, the copy keeps the exact original bytes.',where:'Location',before:'Before',after:'After',previous:'Previous',next:'Next',reportNote:'The JSON report contains all changed locations and original values. The report may itself contain information you do not want to share.',
      copyStep:'04 / COPY',exportTitle:'Make the copy you reviewed',privacy:'This is not anonymization. Names, lyrics, comments and unselected settings remain. Voicebank compatibility and audio reproduction are not guaranteed.',ack:'I reviewed the chosen settings and original values, and understand that unselected information remains.',download:'Export USTX copy',report:'JSON report',print:'Print review',structureTitle:'Part structure stays together',structureHelp:'Review each original part’s position, duration and note count.',track:'Track',part:'Part',position:'Position (ticks)',duration:'Duration (ticks)',limits:'UTF-8 · 8 MiB maximum · USTX 0.10 voice parts only · Up to 2,000 changes per review. Unsupported YAML and invalid data are rejected.',footerScope:'Local processing · no account · no network requests',sourceLink:'Source and verification',
      loading:'Checking the supplied file…',ready:'Source data checked. Choose the settings to clear.',updated:'Selection updated. Review acknowledgment has been cleared.',downloaded:'USTX copy exported. The original file was not changed.',reportSaved:'JSON review exported.',exporting:'Preparing the reviewed copy…',empty:'File and review cleared.',bad:'Cannot read this file. Check the supported format, YAML syntax and input limits.',size:'File exceeds the 8 MiB limit. Its body was not read.',file:'Choose exactly one file with the .ustx extension.',tooMany:'More than 2,000 changes are selected. Reduce the selection and review again.',failedExport:'The copy could not be created. Review acknowledgment has been cleared.',removed:'Removed',notPresent:'Not present',noneAvailable:'No values of this kind.',affected:(c)=>`Affected: ${c.tracks} tracks · ${c.parts} parts · ${c.notes} notes`,range:(a,b,n)=>`${a}–${b} of ${n}`,noteLabel:(n)=>`Note ${n}`,phonemeLabel:(n)=>`Phoneme ${n}`,partFallback:(n)=>`Part ${n}`,trackFallback:(n)=>`Track ${n}`,
      fieldNames:{phoneme:'Phoneme alias',offset:'Phoneme offset',preutter_delta:'Preutterance delta',overlap_delta:'Overlap delta',attack_time_delta:'Attack delta',release_time_delta:'Release delta',singer:'Singer ID',track_color:'Track color',renderer:'Renderer',resampler:'Resampler',wavtool:'Wavtool'}
    }
  };
  function text(key){return words[language][key];}
  function emptyPolicy(){return {singer:false,render:false,trackColor:false,phonemeOverrideFields:[],phonemeExpressions:[],curves:[]};}
  function node(tag,className,value){const n=document.createElement(tag);if(className)n.className=className;if(value!==undefined)n.textContent=String(value);return n;}
  function status(key){statusKey=key;$('status').textContent=key?text(key):'';}
  function showError(key,detail=''){errorKey=key;errorDetail=detail;$('error').hidden=!key;$('error').textContent=key?text(key)+(detail?' '+detail:''):'';}
  function controls(){const blocked=!model||busy||!preview||preview.changes.length>MAX_CHANGES;$('download').disabled=blocked||!$('ack').checked;$('report').disabled=!model||busy;$('print').disabled=blocked;$('ack').disabled=!model||busy;}
  function clearView(){model=null;preview=null;conversion=null;policy=emptyPolicy();sourceName='';pageIndex=0;$('ack').checked=false;$('workbench').hidden=true;$('project-name').textContent='';$('source-name').textContent='';$('diff-rows').replaceChildren();$('structure-rows').replaceChildren();for(const id of ['override-options','expression-options','curve-options'])$(id).replaceChildren();for(const id of ['track-count','part-count','note-count','change-count'])$(id).textContent='0';controls();}
  function clear(){revision++;busy=false;clearView();$('file-input').value='';document.body.dataset.state='empty';showError('');status('empty');}
  function changePolicy(){revision++;busy=false;conversion=null;$('ack').checked=false;pageIndex=0;policy={singer:$('policy-singer').checked,render:$('policy-render').checked,trackColor:$('policy-trackColor').checked,phonemeOverrideFields:[],phonemeExpressions:[],curves:[]};for(const input of document.querySelectorAll('input[data-list]:checked'))policy[input.dataset.list].push(input.value);renderReview();status('updated');}
  function labelTrack(index){return model.data.tracks[index].track_name||text('trackFallback')(index+1);}
  function labelPart(index){return model.data.voice_parts[index].name||text('partFallback')(index+1);}
  function descriptor(abbr,track){return model.data.tracks[track].track_expressions?.find(x=>x.abbr===abbr)||model.data.expressions[abbr];}
  function choice(parent,list,value,label,count,detail=''){
    const line=node('label','choice'),input=node('input');input.type='checkbox';input.dataset.list=list;input.value=value;input.checked=policy[list].includes(value);if(list==='phonemeOverrideFields')input.id='override-'+value;
    input.addEventListener('change',changePolicy);const span=node('span');span.append(node('strong','',label));if(detail)span.append(node('small','',detail));line.append(input,span,node('b','',count));parent.append(line);
  }
  function renderOptions(){
    for(const key of ['singer','render','trackColor'])$('policy-'+key).checked=policy[key];
    $('singer-count').textContent=model.data.tracks.filter(t=>own(t,'singer')).length;
    $('render-count').textContent=model.data.tracks.reduce((n,t)=>n+['renderer','resampler','wavtool'].filter(k=>own(t.renderer_settings||{},k)).length,0);
    $('color-count').textContent=model.data.tracks.filter(t=>t.track_color!=='Blue').length;
    const fields=new Map(),expressions=new Map(),curves=new Map();
    for(const p of model.data.voice_parts){
      for(const n of p.notes){for(const o of n.phoneme_overrides||[])for(const field of C.OVERRIDE_FIELDS)if(own(o,field))fields.set(field,(fields.get(field)||0)+1);for(const e of n.phoneme_expressions||[]){const old=expressions.get(e.abbr)||{count:0,name:descriptor(e.abbr,p.track_no)?.name||''};old.count++;expressions.set(e.abbr,old);}}
      for(const c of p.curves||[]){const old=curves.get(c.abbr)||{count:0,name:descriptor(c.abbr,p.track_no)?.name||''};old.count++;curves.set(c.abbr,old);}
    }
    for(const id of ['override-options','expression-options','curve-options'])$(id).replaceChildren();
    for(const field of C.OVERRIDE_FIELDS)if(fields.has(field))choice($('override-options'),'phonemeOverrideFields',field,words[language].fieldNames[field],fields.get(field),field);
    for(const [abbr,v]of [...expressions].sort(([a],[b])=>a.localeCompare(b)))choice($('expression-options'),'phonemeExpressions',abbr,abbr.toUpperCase(),v.count,v.name);
    for(const [abbr,v]of [...curves].sort(([a],[b])=>a.localeCompare(b)))choice($('curve-options'),'curves',abbr,abbr.toUpperCase(),v.count,v.name);
    for(const id of ['override-options','expression-options','curve-options'])if(!$(id).children.length)$(id).append(node('p','empty-options',text('noneAvailable')));
  }
  function describe(change){const p=change.path;if(p[0]==='tracks'){const field=p.at(-1);return {main:labelTrack(p[1]),detail:words[language].fieldNames[field]||field};}const pi=p[1],part=model.data.voice_parts[pi];if(p[2]==='curves')return {main:labelPart(pi),detail:labelTrack(part.track_no)+' · '+String(change.before.abbr).toUpperCase()};const ni=p[3],note=part.notes[ni];let detail=labelPart(pi)+' · '+text('noteLabel')(ni+1)+' · '+note.lyric;if(p[4]==='phoneme_expressions')detail+=' · '+change.before.abbr.toUpperCase()+' · '+text('phonemeLabel')((change.before.index??0)+1);else detail+=' · '+(words[language].fieldNames[p.at(-1)]||p.at(-1));return {main:labelTrack(part.track_no),detail};}
  function formatValue(value){if(value===undefined)return text('notPresent');return typeof value==='string'?value:JSON.stringify(value,null,2);}
  function renderDiff(){if(!preview)return;const all=preview.changes,total=all.length;pageIndex=Math.min(pageIndex,Math.max(0,Math.ceil(total/PAGE_SIZE)-1));const start=printing?0:pageIndex*PAGE_SIZE,rows=printing?all:all.slice(start,start+PAGE_SIZE);$('diff-rows').replaceChildren();
    for(const change of rows){const tr=node('tr'),where=node('td'),before=node('td'),after=node('td'),d=describe(change);where.append(node('span','where-main',d.main),node('span','where-detail',d.detail));before.append(node('pre','value',formatValue(change.before)));after.append(node('span',change.operation==='remove'?'removed':'set-value',change.operation==='remove'?text('removed'):formatValue(change.after)));tr.append(where,before,after);$('diff-rows').append(tr);}
    $('no-changes').hidden=total>0;$('diff-container').hidden=total===0;$('pagination').hidden=total<=PAGE_SIZE||printing;$('previous').disabled=pageIndex===0;$('next').disabled=(pageIndex+1)*PAGE_SIZE>=total;$('page-range').textContent=total?text('range')(start+1,Math.min(start+rows.length,total),total):'';
  }
  function renderReview(){if(!model)return;preview=C.review(model,policy);$('change-count').textContent=preview.changes.length;$('affected-counts').textContent=text('affected')(preview.counts);renderDiff();const blocked=preview.changes.length>MAX_CHANGES;document.body.dataset.state=blocked?'blocked':'ready';showError(blocked?'tooMany':'');controls();}
  function renderStructure(){$('structure-rows').replaceChildren();model.data.voice_parts.forEach((p,i)=>{const tr=node('tr');for(const value of [labelTrack(p.track_no),labelPart(i),p.position,p.duration,p.notes.length])tr.append(node('td','',value));$('structure-rows').append(tr);});}
  function renderModel(){$('workbench').hidden=false;$('project-name').textContent=model.data.name||'USTX';$('source-name').textContent=sourceName+' · '+model.sourceBytes.toLocaleString(language)+' B';$('track-count').textContent=model.counts.tracks;$('part-count').textContent=model.counts.parts;$('note-count').textContent=model.counts.notes;renderOptions();renderReview();renderStructure();}
  function translate(){document.documentElement.lang=language;for(const n of document.querySelectorAll('[data-i18n]'))n.textContent=text(n.dataset.i18n);$('lang-ja').setAttribute('aria-pressed',String(language==='ja'));$('lang-en').setAttribute('aria-pressed',String(language==='en'));status(statusKey);showError(errorKey,errorDetail);if(model)renderModel();}
  async function ingest(files){const token=++revision;busy=true;clearView();showError('');status('loading');document.body.dataset.state='loading';let name='';try{
      if(files.length!==1||!/\.ustx$/i.test(files[0].name))throw {uiKey:'file'};const file=files[0];name=file.name;if(file.size>C.LIMITS.bytes)throw {uiKey:'size'};
      const bytes=new Uint8Array(await file.arrayBuffer());if(token!==revision)return;const inspected=await C.inspect(bytes);if(token!==revision)return;
      model=inspected;sourceName=name;policy=emptyPolicy();busy=false;renderModel();status('ready');
    }catch(error){if(token!==revision)return;busy=false;clearView();document.body.dataset.state='error';status('');showError(error.uiKey||'bad',error.uiKey?'':String(error.message||''));}finally{if(token===revision){busy=false;controls();}}
  }
  function save(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=node('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function outputName(){const stem=sourceName.replace(/\.ustx$/i,'').replace(/[^\p{L}\p{N} _.-]/gu,'_').slice(0,90)||'project';return stem+'-sharing-copy.ustx';}
  async function obtainConversion(token){if(conversion)return conversion;const result=await C.convert(model,policy,{acknowledged:true});if(token!==revision)return null;conversion=result;return result;}
  async function exportCopy(){if(!model||busy||!$('ack').checked||preview.changes.length>MAX_CHANGES)return;const token=revision;busy=true;controls();status('exporting');try{const result=await obtainConversion(token);if(!result||token!==revision||!$('ack').checked)return;save(result.output,outputName(),'application/yaml');status('downloaded');}catch(error){if(token===revision){$('ack').checked=false;showError('failedExport',String(error.message||''));}}finally{if(token===revision){busy=false;controls();}}}
  async function exportReport(){if(!model||busy)return;const token=revision;busy=true;controls();try{const result=$('ack').checked&&preview.changes.length<=MAX_CHANGES?await obtainConversion(token):{report:preview.report};if(!result||token!==revision)return;save(JSON.stringify(result.report,null,2)+'\n','voice-slate-review.json','application/json');status('reportSaved');}catch(error){if(token===revision)showError('failedExport',String(error.message||''));}finally{if(token===revision){busy=false;controls();}}}
  $('file-input').addEventListener('change',event=>{if(!event.target.files.length){clear();return;}ingest([...event.target.files]);});
  $('sample').addEventListener('click',()=>ingest([new File([globalThis.VoiceSlateSample.text],globalThis.VoiceSlateSample.name,{type:'application/yaml'})]));
  $('clear').addEventListener('click',clear);$('lang-ja').addEventListener('click',()=>{language='ja';translate();});$('lang-en').addEventListener('click',()=>{language='en';translate();});
  for(const key of ['singer','render','trackColor'])$('policy-'+key).addEventListener('change',changePolicy);
  $('reset-policy').addEventListener('click',()=>{revision++;busy=false;policy=emptyPolicy();conversion=null;pageIndex=0;$('ack').checked=false;renderOptions();renderReview();status('updated');});
  $('ack').addEventListener('change',controls);$('download').addEventListener('click',exportCopy);$('report').addEventListener('click',exportReport);
  $('previous').addEventListener('click',()=>{pageIndex--;renderDiff();});$('next').addEventListener('click',()=>{pageIndex++;renderDiff();});
  $('print').addEventListener('click',()=>window.print());window.addEventListener('beforeprint',()=>{printing=true;renderDiff();});window.addEventListener('afterprint',()=>{printing=false;renderDiff();});
  const zone=$('drop-zone');zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('dragging');});zone.addEventListener('dragleave',()=>zone.classList.remove('dragging'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('dragging');ingest([...e.dataTransfer.files]);});
  translate();controls();
})();
